services:
  outpost:
    build:
      context: .
      args:
        USER: outpost
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/home/outpost/.ssh