alias dot='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
alias n='nvim'
alias x='xplr'
alias arst='asdf'
alias xclipimg='xclip -selection clipboard -t image/png'
alias maim-clip='maim -s | xclipimg'
alias maim-wind='maim -i (xdotool getactivewindow) | xclipimg'
alias maim-scrn='maim | xclipimg'
